-- MySQL Script generated by MySQL Workbench
-- Sun Aug 27 13:22:04 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema NationalDish
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema NationalDish
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `NationalDish` DEFAULT CHARACTER SET utf8 ;
USE `NationalDish` ;

-- -----------------------------------------------------
-- Table `NationalDish`.`Dishes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NationalDish`.`Dishes` ;

CREATE TABLE IF NOT EXISTS `NationalDish`.`Dishes` (
  `Dishes_ID` INT NOT NULL,
  `NationalDish` VARCHAR(50) NULL,
  PRIMARY KEY (`Dishes_ID`),
  UNIQUE INDEX `Dishes_ID_UNIQUE` (`Dishes_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NationalDish`.`country_region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NationalDish`.`country_region` ;

CREATE TABLE IF NOT EXISTS `NationalDish`.`country_region` (
  `Country_ID` FLOAT NOT NULL,
  `Country` VARCHAR(50) NULL,
  `ISO-alpha3Code` VARCHAR(50) NULL,
  `Region1` VARCHAR(50) NULL,
  `Region2` VARCHAR(50) NULL,
  `Continent` VARCHAR(50) NULL,
  PRIMARY KEY (`Country_ID`),
  UNIQUE INDEX `Country_ID_UNIQUE` (`Country_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NationalDish`.`country_national_dish`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NationalDish`.`country_national_dish` ;

CREATE TABLE IF NOT EXISTS `NationalDish`.`country_national_dish` (
  `Country` VARCHAR(50) NULL,
  `NationalDish` VARCHAR(50) NULL,
  `Country_ID` FLOAT NOT NULL,
  `Dishes_ID` INT NOT NULL,
  INDEX `fk_country_national_dish_country_region1_idx` (`Country_ID` ASC) VISIBLE,
  INDEX `fk_country_national_dish_Dishes1_idx` (`Dishes_ID` ASC) VISIBLE,
  CONSTRAINT `fk_country_national_dish_country_region1`
    FOREIGN KEY (`Country_ID`)
    REFERENCES `NationalDish`.`country_region` (`Country_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_country_national_dish_Dishes1`
    FOREIGN KEY (`Dishes_ID`)
    REFERENCES `NationalDish`.`Dishes` (`Dishes_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NationalDish`.`main_contents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NationalDish`.`main_contents` ;

CREATE TABLE IF NOT EXISTS `NationalDish`.`main_contents` (
  `MainContent` VARCHAR(50) NULL,
  `Dishes_ID` INT NOT NULL,
  INDEX `fk_main_contents_Dishes_idx` (`Dishes_ID` ASC) VISIBLE,
  CONSTRAINT `Dish identifier`
    FOREIGN KEY (`Dishes_ID`)
    REFERENCES `NationalDish`.`Dishes` (`Dishes_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NationalDish`.`Micronutrients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NationalDish`.`Micronutrients` ;

CREATE TABLE IF NOT EXISTS `NationalDish`.`Micronutrients` (
  `Dishes_ID` INT NOT NULL,
  INDEX `fk_Micronutrients_Dishes1_idx` (`Dishes_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Micronutrients_Dishes1`
    FOREIGN KEY (`Dishes_ID`)
    REFERENCES `NationalDish`.`Dishes` (`Dishes_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NationalDish`.`Macronutrients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NationalDish`.`Macronutrients` ;

CREATE TABLE IF NOT EXISTS `NationalDish`.`Macronutrients` (
  `Dishes_ID` INT NOT NULL,
  INDEX `fk_Macronutrients_Dishes1_idx` (`Dishes_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Macronutrients_Dishes1`
    FOREIGN KEY (`Dishes_ID`)
    REFERENCES `NationalDish`.`Dishes` (`Dishes_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NationalDish`.`life_expectancy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NationalDish`.`life_expectancy` ;

CREATE TABLE IF NOT EXISTS `NationalDish`.`life_expectancy` (
  `Country` VARCHAR(50) NULL,
  `LifeExpectancy` VARCHAR(50) NULL,
  `FemalesLifeExpectancy` VARCHAR(50) NULL,
  `MalesLifeExpectancy` VARCHAR(50) NULL,
  `Country_ID` FLOAT NOT NULL,
  INDEX `fk_life_expectancy_country_region1_idx` (`Country_ID` ASC) VISIBLE,
  CONSTRAINT `fk_life_expectancy_country_region1`
    FOREIGN KEY (`Country_ID`)
    REFERENCES `NationalDish`.`country_region` (`Country_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
